# Generated by Django 3.2.8 on 2021-10-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('number', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
